from pathlib import Path


PROJECT_DIR = Path(__file__).resolve().parents[2]
DATA_DIR = PROJECT_DIR / "data"
FACES_DIR = DATA_DIR / "faces"
PLAYERS_DIR = DATA_DIR / "players"
BASE_FILE = DATA_DIR / "known_faces.pkl"
SESSION_FILE = DATA_DIR / "mafia_session.json"
GAME_FILE = DATA_DIR / "mafia_game.json"

FACE_MATCH_THRESHOLD = 0.60
UNKNOWN_MARGIN = 0.06
ENCODING_ADD_MIN_DISTANCE = 0.035
ENCODING_ADD_MAX_DISTANCE = 0.52
ENCODING_ADD_AMBIGUOUS_MARGIN = 0.045
MAX_ENCODINGS_PER_FACE = 24
MIN_FACE_CROP_SIZE = 42

DETECTION_SCALE = 0.30
DETECTION_FRAME_INTERVAL = 4
MAX_FACES_PER_FRAME = 4
REGISTER_STABLE_FRAMES = 3
VISIBILITY_LOST_TIMEOUT_SEC = 2.0
TRACK_HOLD_FRAMES = 12
TRACK_MAX_MISSING_FRAMES = 30
POSITION_IOU_THRESHOLD = 0.20
POSITION_CENTER_RATIO_THRESHOLD = 0.45
ENCODING_ADD_COOLDOWN_FRAMES = 10
WORKER_COUNT_LIMIT = 4

CAPTURE_WIDTH = 1280
CAPTURE_HEIGHT = 720
CAPTURE_FPS = 30
